/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as EmergenciaRouteImport } from './routes/emergencia'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmergenciaTokenRouteImport } from './routes/emergencia.$token'
import { Route as FamiliaFamilyIdMedicamentosRouteImport } from './routes/familia.$familyId.medicamentos'
import { Route as FamiliaFamilyIdHistoricoRouteImport } from './routes/familia.$familyId.historico'
import { Route as FamiliaFamilyIdDocumentosRouteImport } from './routes/familia.$familyId.documentos'
import { Route as FamiliaFamilyIdAgendaRouteImport } from './routes/familia.$familyId.agenda'
import { Route as FamiliaFamilyIdMedicamentosNovoRouteImport } from './routes/familia.$familyId.medicamentos.novo'
import { Route as FamiliaFamilyIdMedicamentosMedIdRouteImport } from './routes/familia.$familyId.medicamentos.$medId'
import { Route as FamiliaFamilyIdHistoricoNovoRouteImport } from './routes/familia.$familyId.historico.novo'
import { Route as FamiliaFamilyIdHistoricoIdRouteImport } from './routes/familia.$familyId.historico.$id'
import { Route as FamiliaFamilyIdDocumentosNovoRouteImport } from './routes/familia.$familyId.documentos.novo'
import { Route as FamiliaFamilyIdDocumentosIdRouteImport } from './routes/familia.$familyId.documentos.$id'
import { Route as FamiliaFamilyIdAgendaNovoRouteImport } from './routes/familia.$familyId.agenda.novo'
import { Route as FamiliaFamilyIdAgendaIdRouteImport } from './routes/familia.$familyId.agenda.$id'
import { Route as FamiliaFamilyIdMedicamentosMedIdEditarRouteImport } from './routes/familia.$familyId.medicamentos.$medId.editar'
import { Route as FamiliaFamilyIdHistoricoIdEditarRouteImport } from './routes/familia.$familyId.historico.$id.editar'
import { Route as FamiliaFamilyIdAgendaIdEditarRouteImport } from './routes/familia.$familyId.agenda.$id.editar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaRoute = EmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaTokenRoute = EmergenciaTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => EmergenciaRoute,
} as any)
const FamiliaFamilyIdMedicamentosRoute =
  FamiliaFamilyIdMedicamentosRouteImport.update({
    id: '/$familyId/medicamentos',
    path: '/$familyId/medicamentos',
    getParentRoute: () => FamiliaRoute,
  } as any)
const FamiliaFamilyIdHistoricoRoute =
  FamiliaFamilyIdHistoricoRouteImport.update({
    id: '/$familyId/historico',
    path: '/$familyId/historico',
    getParentRoute: () => FamiliaRoute,
  } as any)
const FamiliaFamilyIdDocumentosRoute =
  FamiliaFamilyIdDocumentosRouteImport.update({
    id: '/$familyId/documentos',
    path: '/$familyId/documentos',
    getParentRoute: () => FamiliaRoute,
  } as any)
const FamiliaFamilyIdAgendaRoute = FamiliaFamilyIdAgendaRouteImport.update({
  id: '/$familyId/agenda',
  path: '/$familyId/agenda',
  getParentRoute: () => FamiliaRoute,
} as any)
const FamiliaFamilyIdMedicamentosNovoRoute =
  FamiliaFamilyIdMedicamentosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => FamiliaFamilyIdMedicamentosRoute,
  } as any)
const FamiliaFamilyIdMedicamentosMedIdRoute =
  FamiliaFamilyIdMedicamentosMedIdRouteImport.update({
    id: '/$medId',
    path: '/$medId',
    getParentRoute: () => FamiliaFamilyIdMedicamentosRoute,
  } as any)
const FamiliaFamilyIdHistoricoNovoRoute =
  FamiliaFamilyIdHistoricoNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => FamiliaFamilyIdHistoricoRoute,
  } as any)
const FamiliaFamilyIdHistoricoIdRoute =
  FamiliaFamilyIdHistoricoIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => FamiliaFamilyIdHistoricoRoute,
  } as any)
const FamiliaFamilyIdDocumentosNovoRoute =
  FamiliaFamilyIdDocumentosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => FamiliaFamilyIdDocumentosRoute,
  } as any)
const FamiliaFamilyIdDocumentosIdRoute =
  FamiliaFamilyIdDocumentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => FamiliaFamilyIdDocumentosRoute,
  } as any)
const FamiliaFamilyIdAgendaNovoRoute =
  FamiliaFamilyIdAgendaNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => FamiliaFamilyIdAgendaRoute,
  } as any)
const FamiliaFamilyIdAgendaIdRoute = FamiliaFamilyIdAgendaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FamiliaFamilyIdAgendaRoute,
} as any)
const FamiliaFamilyIdMedicamentosMedIdEditarRoute =
  FamiliaFamilyIdMedicamentosMedIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => FamiliaFamilyIdMedicamentosMedIdRoute,
  } as any)
const FamiliaFamilyIdHistoricoIdEditarRoute =
  FamiliaFamilyIdHistoricoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => FamiliaFamilyIdHistoricoIdRoute,
  } as any)
const FamiliaFamilyIdAgendaIdEditarRoute =
  FamiliaFamilyIdAgendaIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => FamiliaFamilyIdAgendaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/emergencia': typeof EmergenciaRouteWithChildren
  '/familia': typeof FamiliaRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/emergencia/$token': typeof EmergenciaTokenRoute
  '/familia/$familyId/agenda': typeof FamiliaFamilyIdAgendaRouteWithChildren
  '/familia/$familyId/documentos': typeof FamiliaFamilyIdDocumentosRouteWithChildren
  '/familia/$familyId/historico': typeof FamiliaFamilyIdHistoricoRouteWithChildren
  '/familia/$familyId/medicamentos': typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  '/familia/$familyId/agenda/$id': typeof FamiliaFamilyIdAgendaIdRouteWithChildren
  '/familia/$familyId/agenda/novo': typeof FamiliaFamilyIdAgendaNovoRoute
  '/familia/$familyId/documentos/$id': typeof FamiliaFamilyIdDocumentosIdRoute
  '/familia/$familyId/documentos/novo': typeof FamiliaFamilyIdDocumentosNovoRoute
  '/familia/$familyId/historico/$id': typeof FamiliaFamilyIdHistoricoIdRouteWithChildren
  '/familia/$familyId/historico/novo': typeof FamiliaFamilyIdHistoricoNovoRoute
  '/familia/$familyId/medicamentos/$medId': typeof FamiliaFamilyIdMedicamentosMedIdRouteWithChildren
  '/familia/$familyId/medicamentos/novo': typeof FamiliaFamilyIdMedicamentosNovoRoute
  '/familia/$familyId/agenda/$id/editar': typeof FamiliaFamilyIdAgendaIdEditarRoute
  '/familia/$familyId/historico/$id/editar': typeof FamiliaFamilyIdHistoricoIdEditarRoute
  '/familia/$familyId/medicamentos/$medId/editar': typeof FamiliaFamilyIdMedicamentosMedIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/emergencia': typeof EmergenciaRouteWithChildren
  '/familia': typeof FamiliaRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/emergencia/$token': typeof EmergenciaTokenRoute
  '/familia/$familyId/agenda': typeof FamiliaFamilyIdAgendaRouteWithChildren
  '/familia/$familyId/documentos': typeof FamiliaFamilyIdDocumentosRouteWithChildren
  '/familia/$familyId/historico': typeof FamiliaFamilyIdHistoricoRouteWithChildren
  '/familia/$familyId/medicamentos': typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  '/familia/$familyId/agenda/$id': typeof FamiliaFamilyIdAgendaIdRouteWithChildren
  '/familia/$familyId/agenda/novo': typeof FamiliaFamilyIdAgendaNovoRoute
  '/familia/$familyId/documentos/$id': typeof FamiliaFamilyIdDocumentosIdRoute
  '/familia/$familyId/documentos/novo': typeof FamiliaFamilyIdDocumentosNovoRoute
  '/familia/$familyId/historico/$id': typeof FamiliaFamilyIdHistoricoIdRouteWithChildren
  '/familia/$familyId/historico/novo': typeof FamiliaFamilyIdHistoricoNovoRoute
  '/familia/$familyId/medicamentos/$medId': typeof FamiliaFamilyIdMedicamentosMedIdRouteWithChildren
  '/familia/$familyId/medicamentos/novo': typeof FamiliaFamilyIdMedicamentosNovoRoute
  '/familia/$familyId/agenda/$id/editar': typeof FamiliaFamilyIdAgendaIdEditarRoute
  '/familia/$familyId/historico/$id/editar': typeof FamiliaFamilyIdHistoricoIdEditarRoute
  '/familia/$familyId/medicamentos/$medId/editar': typeof FamiliaFamilyIdMedicamentosMedIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/emergencia': typeof EmergenciaRouteWithChildren
  '/familia': typeof FamiliaRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/emergencia/$token': typeof EmergenciaTokenRoute
  '/familia/$familyId/agenda': typeof FamiliaFamilyIdAgendaRouteWithChildren
  '/familia/$familyId/documentos': typeof FamiliaFamilyIdDocumentosRouteWithChildren
  '/familia/$familyId/historico': typeof FamiliaFamilyIdHistoricoRouteWithChildren
  '/familia/$familyId/medicamentos': typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  '/familia/$familyId/agenda/$id': typeof FamiliaFamilyIdAgendaIdRouteWithChildren
  '/familia/$familyId/agenda/novo': typeof FamiliaFamilyIdAgendaNovoRoute
  '/familia/$familyId/documentos/$id': typeof FamiliaFamilyIdDocumentosIdRoute
  '/familia/$familyId/documentos/novo': typeof FamiliaFamilyIdDocumentosNovoRoute
  '/familia/$familyId/historico/$id': typeof FamiliaFamilyIdHistoricoIdRouteWithChildren
  '/familia/$familyId/historico/novo': typeof FamiliaFamilyIdHistoricoNovoRoute
  '/familia/$familyId/medicamentos/$medId': typeof FamiliaFamilyIdMedicamentosMedIdRouteWithChildren
  '/familia/$familyId/medicamentos/novo': typeof FamiliaFamilyIdMedicamentosNovoRoute
  '/familia/$familyId/agenda/$id/editar': typeof FamiliaFamilyIdAgendaIdEditarRoute
  '/familia/$familyId/historico/$id/editar': typeof FamiliaFamilyIdHistoricoIdEditarRoute
  '/familia/$familyId/medicamentos/$medId/editar': typeof FamiliaFamilyIdMedicamentosMedIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/documentos'
    | '/emergencia'
    | '/familia'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/register'
    | '/emergencia/$token'
    | '/familia/$familyId/agenda'
    | '/familia/$familyId/documentos'
    | '/familia/$familyId/historico'
    | '/familia/$familyId/medicamentos'
    | '/familia/$familyId/agenda/$id'
    | '/familia/$familyId/agenda/novo'
    | '/familia/$familyId/documentos/$id'
    | '/familia/$familyId/documentos/novo'
    | '/familia/$familyId/historico/$id'
    | '/familia/$familyId/historico/novo'
    | '/familia/$familyId/medicamentos/$medId'
    | '/familia/$familyId/medicamentos/novo'
    | '/familia/$familyId/agenda/$id/editar'
    | '/familia/$familyId/historico/$id/editar'
    | '/familia/$familyId/medicamentos/$medId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/documentos'
    | '/emergencia'
    | '/familia'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/register'
    | '/emergencia/$token'
    | '/familia/$familyId/agenda'
    | '/familia/$familyId/documentos'
    | '/familia/$familyId/historico'
    | '/familia/$familyId/medicamentos'
    | '/familia/$familyId/agenda/$id'
    | '/familia/$familyId/agenda/novo'
    | '/familia/$familyId/documentos/$id'
    | '/familia/$familyId/documentos/novo'
    | '/familia/$familyId/historico/$id'
    | '/familia/$familyId/historico/novo'
    | '/familia/$familyId/medicamentos/$medId'
    | '/familia/$familyId/medicamentos/novo'
    | '/familia/$familyId/agenda/$id/editar'
    | '/familia/$familyId/historico/$id/editar'
    | '/familia/$familyId/medicamentos/$medId/editar'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/documentos'
    | '/emergencia'
    | '/familia'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/register'
    | '/emergencia/$token'
    | '/familia/$familyId/agenda'
    | '/familia/$familyId/documentos'
    | '/familia/$familyId/historico'
    | '/familia/$familyId/medicamentos'
    | '/familia/$familyId/agenda/$id'
    | '/familia/$familyId/agenda/novo'
    | '/familia/$familyId/documentos/$id'
    | '/familia/$familyId/documentos/novo'
    | '/familia/$familyId/historico/$id'
    | '/familia/$familyId/historico/novo'
    | '/familia/$familyId/medicamentos/$medId'
    | '/familia/$familyId/medicamentos/novo'
    | '/familia/$familyId/agenda/$id/editar'
    | '/familia/$familyId/historico/$id/editar'
    | '/familia/$familyId/medicamentos/$medId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  EmergenciaRoute: typeof EmergenciaRouteWithChildren
  FamiliaRoute: typeof FamiliaRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia': {
      id: '/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof EmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia/$token': {
      id: '/emergencia/$token'
      path: '/$token'
      fullPath: '/emergencia/$token'
      preLoaderRoute: typeof EmergenciaTokenRouteImport
      parentRoute: typeof EmergenciaRoute
    }
    '/familia/$familyId/medicamentos': {
      id: '/familia/$familyId/medicamentos'
      path: '/$familyId/medicamentos'
      fullPath: '/familia/$familyId/medicamentos'
      preLoaderRoute: typeof FamiliaFamilyIdMedicamentosRouteImport
      parentRoute: typeof FamiliaRoute
    }
    '/familia/$familyId/historico': {
      id: '/familia/$familyId/historico'
      path: '/$familyId/historico'
      fullPath: '/familia/$familyId/historico'
      preLoaderRoute: typeof FamiliaFamilyIdHistoricoRouteImport
      parentRoute: typeof FamiliaRoute
    }
    '/familia/$familyId/documentos': {
      id: '/familia/$familyId/documentos'
      path: '/$familyId/documentos'
      fullPath: '/familia/$familyId/documentos'
      preLoaderRoute: typeof FamiliaFamilyIdDocumentosRouteImport
      parentRoute: typeof FamiliaRoute
    }
    '/familia/$familyId/agenda': {
      id: '/familia/$familyId/agenda'
      path: '/$familyId/agenda'
      fullPath: '/familia/$familyId/agenda'
      preLoaderRoute: typeof FamiliaFamilyIdAgendaRouteImport
      parentRoute: typeof FamiliaRoute
    }
    '/familia/$familyId/medicamentos/novo': {
      id: '/familia/$familyId/medicamentos/novo'
      path: '/novo'
      fullPath: '/familia/$familyId/medicamentos/novo'
      preLoaderRoute: typeof FamiliaFamilyIdMedicamentosNovoRouteImport
      parentRoute: typeof FamiliaFamilyIdMedicamentosRoute
    }
    '/familia/$familyId/medicamentos/$medId': {
      id: '/familia/$familyId/medicamentos/$medId'
      path: '/$medId'
      fullPath: '/familia/$familyId/medicamentos/$medId'
      preLoaderRoute: typeof FamiliaFamilyIdMedicamentosMedIdRouteImport
      parentRoute: typeof FamiliaFamilyIdMedicamentosRoute
    }
    '/familia/$familyId/historico/novo': {
      id: '/familia/$familyId/historico/novo'
      path: '/novo'
      fullPath: '/familia/$familyId/historico/novo'
      preLoaderRoute: typeof FamiliaFamilyIdHistoricoNovoRouteImport
      parentRoute: typeof FamiliaFamilyIdHistoricoRoute
    }
    '/familia/$familyId/historico/$id': {
      id: '/familia/$familyId/historico/$id'
      path: '/$id'
      fullPath: '/familia/$familyId/historico/$id'
      preLoaderRoute: typeof FamiliaFamilyIdHistoricoIdRouteImport
      parentRoute: typeof FamiliaFamilyIdHistoricoRoute
    }
    '/familia/$familyId/documentos/novo': {
      id: '/familia/$familyId/documentos/novo'
      path: '/novo'
      fullPath: '/familia/$familyId/documentos/novo'
      preLoaderRoute: typeof FamiliaFamilyIdDocumentosNovoRouteImport
      parentRoute: typeof FamiliaFamilyIdDocumentosRoute
    }
    '/familia/$familyId/documentos/$id': {
      id: '/familia/$familyId/documentos/$id'
      path: '/$id'
      fullPath: '/familia/$familyId/documentos/$id'
      preLoaderRoute: typeof FamiliaFamilyIdDocumentosIdRouteImport
      parentRoute: typeof FamiliaFamilyIdDocumentosRoute
    }
    '/familia/$familyId/agenda/novo': {
      id: '/familia/$familyId/agenda/novo'
      path: '/novo'
      fullPath: '/familia/$familyId/agenda/novo'
      preLoaderRoute: typeof FamiliaFamilyIdAgendaNovoRouteImport
      parentRoute: typeof FamiliaFamilyIdAgendaRoute
    }
    '/familia/$familyId/agenda/$id': {
      id: '/familia/$familyId/agenda/$id'
      path: '/$id'
      fullPath: '/familia/$familyId/agenda/$id'
      preLoaderRoute: typeof FamiliaFamilyIdAgendaIdRouteImport
      parentRoute: typeof FamiliaFamilyIdAgendaRoute
    }
    '/familia/$familyId/medicamentos/$medId/editar': {
      id: '/familia/$familyId/medicamentos/$medId/editar'
      path: '/editar'
      fullPath: '/familia/$familyId/medicamentos/$medId/editar'
      preLoaderRoute: typeof FamiliaFamilyIdMedicamentosMedIdEditarRouteImport
      parentRoute: typeof FamiliaFamilyIdMedicamentosMedIdRoute
    }
    '/familia/$familyId/historico/$id/editar': {
      id: '/familia/$familyId/historico/$id/editar'
      path: '/editar'
      fullPath: '/familia/$familyId/historico/$id/editar'
      preLoaderRoute: typeof FamiliaFamilyIdHistoricoIdEditarRouteImport
      parentRoute: typeof FamiliaFamilyIdHistoricoIdRoute
    }
    '/familia/$familyId/agenda/$id/editar': {
      id: '/familia/$familyId/agenda/$id/editar'
      path: '/editar'
      fullPath: '/familia/$familyId/agenda/$id/editar'
      preLoaderRoute: typeof FamiliaFamilyIdAgendaIdEditarRouteImport
      parentRoute: typeof FamiliaFamilyIdAgendaIdRoute
    }
  }
}

interface EmergenciaRouteChildren {
  EmergenciaTokenRoute: typeof EmergenciaTokenRoute
}

const EmergenciaRouteChildren: EmergenciaRouteChildren = {
  EmergenciaTokenRoute: EmergenciaTokenRoute,
}

const EmergenciaRouteWithChildren = EmergenciaRoute._addFileChildren(
  EmergenciaRouteChildren,
)

interface FamiliaFamilyIdAgendaIdRouteChildren {
  FamiliaFamilyIdAgendaIdEditarRoute: typeof FamiliaFamilyIdAgendaIdEditarRoute
}

const FamiliaFamilyIdAgendaIdRouteChildren: FamiliaFamilyIdAgendaIdRouteChildren =
  {
    FamiliaFamilyIdAgendaIdEditarRoute: FamiliaFamilyIdAgendaIdEditarRoute,
  }

const FamiliaFamilyIdAgendaIdRouteWithChildren =
  FamiliaFamilyIdAgendaIdRoute._addFileChildren(
    FamiliaFamilyIdAgendaIdRouteChildren,
  )

interface FamiliaFamilyIdAgendaRouteChildren {
  FamiliaFamilyIdAgendaIdRoute: typeof FamiliaFamilyIdAgendaIdRouteWithChildren
  FamiliaFamilyIdAgendaNovoRoute: typeof FamiliaFamilyIdAgendaNovoRoute
}

const FamiliaFamilyIdAgendaRouteChildren: FamiliaFamilyIdAgendaRouteChildren = {
  FamiliaFamilyIdAgendaIdRoute: FamiliaFamilyIdAgendaIdRouteWithChildren,
  FamiliaFamilyIdAgendaNovoRoute: FamiliaFamilyIdAgendaNovoRoute,
}

const FamiliaFamilyIdAgendaRouteWithChildren =
  FamiliaFamilyIdAgendaRoute._addFileChildren(
    FamiliaFamilyIdAgendaRouteChildren,
  )

interface FamiliaFamilyIdDocumentosRouteChildren {
  FamiliaFamilyIdDocumentosIdRoute: typeof FamiliaFamilyIdDocumentosIdRoute
  FamiliaFamilyIdDocumentosNovoRoute: typeof FamiliaFamilyIdDocumentosNovoRoute
}

const FamiliaFamilyIdDocumentosRouteChildren: FamiliaFamilyIdDocumentosRouteChildren =
  {
    FamiliaFamilyIdDocumentosIdRoute: FamiliaFamilyIdDocumentosIdRoute,
    FamiliaFamilyIdDocumentosNovoRoute: FamiliaFamilyIdDocumentosNovoRoute,
  }

const FamiliaFamilyIdDocumentosRouteWithChildren =
  FamiliaFamilyIdDocumentosRoute._addFileChildren(
    FamiliaFamilyIdDocumentosRouteChildren,
  )

interface FamiliaFamilyIdHistoricoIdRouteChildren {
  FamiliaFamilyIdHistoricoIdEditarRoute: typeof FamiliaFamilyIdHistoricoIdEditarRoute
}

const FamiliaFamilyIdHistoricoIdRouteChildren: FamiliaFamilyIdHistoricoIdRouteChildren =
  {
    FamiliaFamilyIdHistoricoIdEditarRoute:
      FamiliaFamilyIdHistoricoIdEditarRoute,
  }

const FamiliaFamilyIdHistoricoIdRouteWithChildren =
  FamiliaFamilyIdHistoricoIdRoute._addFileChildren(
    FamiliaFamilyIdHistoricoIdRouteChildren,
  )

interface FamiliaFamilyIdHistoricoRouteChildren {
  FamiliaFamilyIdHistoricoIdRoute: typeof FamiliaFamilyIdHistoricoIdRouteWithChildren
  FamiliaFamilyIdHistoricoNovoRoute: typeof FamiliaFamilyIdHistoricoNovoRoute
}

const FamiliaFamilyIdHistoricoRouteChildren: FamiliaFamilyIdHistoricoRouteChildren =
  {
    FamiliaFamilyIdHistoricoIdRoute:
      FamiliaFamilyIdHistoricoIdRouteWithChildren,
    FamiliaFamilyIdHistoricoNovoRoute: FamiliaFamilyIdHistoricoNovoRoute,
  }

const FamiliaFamilyIdHistoricoRouteWithChildren =
  FamiliaFamilyIdHistoricoRoute._addFileChildren(
    FamiliaFamilyIdHistoricoRouteChildren,
  )

interface FamiliaFamilyIdMedicamentosMedIdRouteChildren {
  FamiliaFamilyIdMedicamentosMedIdEditarRoute: typeof FamiliaFamilyIdMedicamentosMedIdEditarRoute
}

const FamiliaFamilyIdMedicamentosMedIdRouteChildren: FamiliaFamilyIdMedicamentosMedIdRouteChildren =
  {
    FamiliaFamilyIdMedicamentosMedIdEditarRoute:
      FamiliaFamilyIdMedicamentosMedIdEditarRoute,
  }

const FamiliaFamilyIdMedicamentosMedIdRouteWithChildren =
  FamiliaFamilyIdMedicamentosMedIdRoute._addFileChildren(
    FamiliaFamilyIdMedicamentosMedIdRouteChildren,
  )

interface FamiliaFamilyIdMedicamentosRouteChildren {
  FamiliaFamilyIdMedicamentosMedIdRoute: typeof FamiliaFamilyIdMedicamentosMedIdRouteWithChildren
  FamiliaFamilyIdMedicamentosNovoRoute: typeof FamiliaFamilyIdMedicamentosNovoRoute
}

const FamiliaFamilyIdMedicamentosRouteChildren: FamiliaFamilyIdMedicamentosRouteChildren =
  {
    FamiliaFamilyIdMedicamentosMedIdRoute:
      FamiliaFamilyIdMedicamentosMedIdRouteWithChildren,
    FamiliaFamilyIdMedicamentosNovoRoute: FamiliaFamilyIdMedicamentosNovoRoute,
  }

const FamiliaFamilyIdMedicamentosRouteWithChildren =
  FamiliaFamilyIdMedicamentosRoute._addFileChildren(
    FamiliaFamilyIdMedicamentosRouteChildren,
  )

interface FamiliaRouteChildren {
  FamiliaFamilyIdAgendaRoute: typeof FamiliaFamilyIdAgendaRouteWithChildren
  FamiliaFamilyIdDocumentosRoute: typeof FamiliaFamilyIdDocumentosRouteWithChildren
  FamiliaFamilyIdHistoricoRoute: typeof FamiliaFamilyIdHistoricoRouteWithChildren
  FamiliaFamilyIdMedicamentosRoute: typeof FamiliaFamilyIdMedicamentosRouteWithChildren
}

const FamiliaRouteChildren: FamiliaRouteChildren = {
  FamiliaFamilyIdAgendaRoute: FamiliaFamilyIdAgendaRouteWithChildren,
  FamiliaFamilyIdDocumentosRoute: FamiliaFamilyIdDocumentosRouteWithChildren,
  FamiliaFamilyIdHistoricoRoute: FamiliaFamilyIdHistoricoRouteWithChildren,
  FamiliaFamilyIdMedicamentosRoute:
    FamiliaFamilyIdMedicamentosRouteWithChildren,
}

const FamiliaRouteWithChildren =
  FamiliaRoute._addFileChildren(FamiliaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  EmergenciaRoute: EmergenciaRouteWithChildren,
  FamiliaRoute: FamiliaRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
