/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as EmergenciaRouteImport } from './routes/emergencia'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliaFamilyIdMedicamentosRouteImport } from './routes/familia.$familyId.medicamentos'
import { Route as FamiliaFamilyIdMedicamentosNovoRouteImport } from './routes/familia.$familyId.medicamentos.novo'
import { Route as FamiliaFamilyIdDocumentosNovoRouteImport } from './routes/familia.$familyId.documentos.novo'
import { Route as FamiliaFamilyIdAgendaNovoRouteImport } from './routes/familia.$familyId.agenda.novo'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaRoute = EmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaFamilyIdMedicamentosRoute =
  FamiliaFamilyIdMedicamentosRouteImport.update({
    id: '/$familyId/medicamentos',
    path: '/$familyId/medicamentos',
    getParentRoute: () => FamiliaRoute,
  } as any)
const FamiliaFamilyIdMedicamentosNovoRoute =
  FamiliaFamilyIdMedicamentosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => FamiliaFamilyIdMedicamentosRoute,
  } as any)
const FamiliaFamilyIdDocumentosNovoRoute =
  FamiliaFamilyIdDocumentosNovoRouteImport.update({
    id: '/$familyId/documentos/novo',
    path: '/$familyId/documentos/novo',
    getParentRoute: () => FamiliaRoute,
  } as any)
const FamiliaFamilyIdAgendaNovoRoute =
  FamiliaFamilyIdAgendaNovoRouteImport.update({
    id: '/$familyId/agenda/novo',
    path: '/$familyId/agenda/novo',
    getParentRoute: () => FamiliaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/emergencia': typeof EmergenciaRoute
  '/familia': typeof FamiliaRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/familia/$familyId/medicamentos': typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  '/familia/$familyId/agenda/novo': typeof FamiliaFamilyIdAgendaNovoRoute
  '/familia/$familyId/documentos/novo': typeof FamiliaFamilyIdDocumentosNovoRoute
  '/familia/$familyId/medicamentos/novo': typeof FamiliaFamilyIdMedicamentosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/emergencia': typeof EmergenciaRoute
  '/familia': typeof FamiliaRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/familia/$familyId/medicamentos': typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  '/familia/$familyId/agenda/novo': typeof FamiliaFamilyIdAgendaNovoRoute
  '/familia/$familyId/documentos/novo': typeof FamiliaFamilyIdDocumentosNovoRoute
  '/familia/$familyId/medicamentos/novo': typeof FamiliaFamilyIdMedicamentosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/emergencia': typeof EmergenciaRoute
  '/familia': typeof FamiliaRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/familia/$familyId/medicamentos': typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  '/familia/$familyId/agenda/novo': typeof FamiliaFamilyIdAgendaNovoRoute
  '/familia/$familyId/documentos/novo': typeof FamiliaFamilyIdDocumentosNovoRoute
  '/familia/$familyId/medicamentos/novo': typeof FamiliaFamilyIdMedicamentosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/documentos'
    | '/emergencia'
    | '/familia'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/register'
    | '/familia/$familyId/medicamentos'
    | '/familia/$familyId/agenda/novo'
    | '/familia/$familyId/documentos/novo'
    | '/familia/$familyId/medicamentos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/documentos'
    | '/emergencia'
    | '/familia'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/register'
    | '/familia/$familyId/medicamentos'
    | '/familia/$familyId/agenda/novo'
    | '/familia/$familyId/documentos/novo'
    | '/familia/$familyId/medicamentos/novo'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/documentos'
    | '/emergencia'
    | '/familia'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/register'
    | '/familia/$familyId/medicamentos'
    | '/familia/$familyId/agenda/novo'
    | '/familia/$familyId/documentos/novo'
    | '/familia/$familyId/medicamentos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  EmergenciaRoute: typeof EmergenciaRoute
  FamiliaRoute: typeof FamiliaRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia': {
      id: '/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof EmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/$familyId/medicamentos': {
      id: '/familia/$familyId/medicamentos'
      path: '/$familyId/medicamentos'
      fullPath: '/familia/$familyId/medicamentos'
      preLoaderRoute: typeof FamiliaFamilyIdMedicamentosRouteImport
      parentRoute: typeof FamiliaRoute
    }
    '/familia/$familyId/medicamentos/novo': {
      id: '/familia/$familyId/medicamentos/novo'
      path: '/novo'
      fullPath: '/familia/$familyId/medicamentos/novo'
      preLoaderRoute: typeof FamiliaFamilyIdMedicamentosNovoRouteImport
      parentRoute: typeof FamiliaFamilyIdMedicamentosRoute
    }
    '/familia/$familyId/documentos/novo': {
      id: '/familia/$familyId/documentos/novo'
      path: '/$familyId/documentos/novo'
      fullPath: '/familia/$familyId/documentos/novo'
      preLoaderRoute: typeof FamiliaFamilyIdDocumentosNovoRouteImport
      parentRoute: typeof FamiliaRoute
    }
    '/familia/$familyId/agenda/novo': {
      id: '/familia/$familyId/agenda/novo'
      path: '/$familyId/agenda/novo'
      fullPath: '/familia/$familyId/agenda/novo'
      preLoaderRoute: typeof FamiliaFamilyIdAgendaNovoRouteImport
      parentRoute: typeof FamiliaRoute
    }
  }
}

interface FamiliaFamilyIdMedicamentosRouteChildren {
  FamiliaFamilyIdMedicamentosNovoRoute: typeof FamiliaFamilyIdMedicamentosNovoRoute
}

const FamiliaFamilyIdMedicamentosRouteChildren: FamiliaFamilyIdMedicamentosRouteChildren =
  {
    FamiliaFamilyIdMedicamentosNovoRoute: FamiliaFamilyIdMedicamentosNovoRoute,
  }

const FamiliaFamilyIdMedicamentosRouteWithChildren =
  FamiliaFamilyIdMedicamentosRoute._addFileChildren(
    FamiliaFamilyIdMedicamentosRouteChildren,
  )

interface FamiliaRouteChildren {
  FamiliaFamilyIdMedicamentosRoute: typeof FamiliaFamilyIdMedicamentosRouteWithChildren
  FamiliaFamilyIdAgendaNovoRoute: typeof FamiliaFamilyIdAgendaNovoRoute
  FamiliaFamilyIdDocumentosNovoRoute: typeof FamiliaFamilyIdDocumentosNovoRoute
}

const FamiliaRouteChildren: FamiliaRouteChildren = {
  FamiliaFamilyIdMedicamentosRoute:
    FamiliaFamilyIdMedicamentosRouteWithChildren,
  FamiliaFamilyIdAgendaNovoRoute: FamiliaFamilyIdAgendaNovoRoute,
  FamiliaFamilyIdDocumentosNovoRoute: FamiliaFamilyIdDocumentosNovoRoute,
}

const FamiliaRouteWithChildren =
  FamiliaRoute._addFileChildren(FamiliaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  EmergenciaRoute: EmergenciaRoute,
  FamiliaRoute: FamiliaRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
